### ISSUE TITLE
crash in noise example when resizing

### ISSUE THREAD

**Issue by WebFreak001** [brianush1/framed#1]
Getting an assert error in line 29 calling `win.update(data)` because the length of data is not equals to `win.width * win.height`

I believe this is because width/height is querying the OS instead of using the width/height from since the last event queue update and the resize happens while the pixels are drawn.

This will probably become more apparent in higher load redrawing code and the user resizing/maximizing while unresponsive.

**Comment by brianush1** [comment]
How consistently can you reproduce this issue? I can't seem to get it to work.

I don't think the resize can happen after the buffer is resized, though, since events are only processed in calls to `win.yield()` or `win.eventQueue`. At any other time, the window shouldn't be responding to any events, including resize events.

**Comment by WebFreak001** [comment]
I'm using an autohotkey script which force resizes the window using win32 calls, which reproduces it like 100% of the time.

**Comment by WebFreak001** [comment]
fixed now
